Task_1_1_2
Repeynik/OOP pull request #4
Opened 2024-10-02 18:24 UTC by Repeynik

rename branch, but it is still the same

2024-10-08 06:27 UTC, BIGNIKi requested changes

2024-10-08 06:27 UTC, BIGNIKi commented on Task_1_1_2/app/src/main/java/org/task_1_1_2/DefaultPlayer.java
> +    protected List<Cards> deck;
Сделать приватными, если нужны методы get, set, добавить

2024-10-08 06:27 UTC, BIGNIKi commented on Task_1_1_2/app/src/main/java/org/task_1_1_2/DefaultPlayer.java
> +    public int getPlayerScore(List<Cards> cards) {
Не нужно передавать ему его же карты, они уже хранятся в объекте

2024-10-08 06:27 UTC, BIGNIKi commented on Task_1_1_2/app/src/test/java/org/task_1_1_2/DefaultPlayerTest.java
> +        player.abstractCards.add(player.deck.get(7));
Волшебные числа упаковать в enum в тестовом пакете

2024-10-08 06:27 UTC, BIGNIKi commented on Task_1_1_2/app/src/main/java/org/task_1_1_2/DefaultPlayer.java
> +    public void hit() {
Назвать нормально

2024-10-08 06:27 UTC, BIGNIKi commented on Task_1_1_2/app/src/main/java/org/enums/GameState.java
> +    public int getGameSituation(Cards[] cards, boolean blackJackState) {
Вынести логику из enum`ов

2024-10-15 05:41 UTC, BIGNIKi approved these changes

2024-11-25 14:16 UTC, Repeynik commented
add task

2024-11-29 06:10 UTC, merged